site_name: Tim's Website
theme: yeti
site_description: A website about my stuff
site_author: Tim Hollabaugh
site_favicon: null
docs_dir: src
repo_url: https://github.com/timothyhollabaugh
pages:
  - Home: index.md
  - Robostorm:
    - Club: robostorm.md
    - Aquabot: aquabot.md
    - Battlebots: battlebots.md
    - Nametag Web App: nametagautoprinting.md
  - FIRST: daleks.md
  - Projects:
    - 3d Printer: 3dprinter.md
    - PCB Mill: cyclone.md
    - Mini Tricopter: minitricopter.md
    - Large Tricopter: largetricopter.md
    - Slotcar Lap Counter: lapcounter.md
  - PPPL: pppl.md
